#!/bin/bash
. config/env.config

RUN_MULTITHREADED=false
CONFIG_DIR=$(pwd)/config
SQL_TOOLS_DIR=$CONFIG_DIR/sql #contains all SQL files to be imported before the ones generated by OpenMapTiles project
LAYER_FILE=$CONFIG_DIR/$EXPORT_LAYER_FILE
EXPORT_DIR=$(pwd)/data
SQL_DIR=$EXPORT_DIR/sql


if [ ! -d "$EXPORT_DIR" ]; then mkdir -p $EXPORT_DIR; fi
if [ -d "$SQL_DIR" ]; then rm -Rf $SQL_DIR; fi
if [ ! -d "$SQL_DIR" ]; then mkdir -p $SQL_DIR; fi


if [ "$RUN_MULTITHREADED" == true ]; then
	echo "MULTI-THREADED"
	#Create Parallel SQL
	generate-sql $LAYER_FILE --dir $SQL_DIR

	#Load Parallel SQL
	export PGHOST=$POSTGRES_HOST
	export PGPORT=$POSTGRES_PORT
	export PGDATABASE=$POSTGRES_DB
	export PGUSER=$POSTGRES_USER
	export PGPASSWORD=$POSTGRES_PASS
	export SQL_TOOLS_DIR=$SQL_TOOLS_DIR
	export SQL_DIR=$SQL_DIR
	import-sql
else
	#Load Needed SQL Functions
	for i in `find $SQL_TOOLS_DIR -name "*.sql" -type f|sort -d`; do
		echo "-- $i --"
		PGPASSWORD=$POSTGRES_PASS psql -h $POSTGRES_HOST -d $POSTGRES_DB -U "$POSTGRES_USER" -f $i
	done

	echo "Single-THREADED"
	#Create Tileset SQL
	generate-sql $LAYER_FILE > $SQL_DIR/tileset.sql
	
	#Load Tileset SQL
	echo "-- tileset.sql --"
	PGPASSWORD=$POSTGRES_PASS psql -h $POSTGRES_HOST -d $POSTGRES_DB -U "$POSTGRES_USER" -f $SQL_DIR/tileset.sql	
fi









