name: Build

runs:
    using: composite

    steps:
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -LA .. \
           -DBUILD_DATA_TESTS=ON \
           -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
           -DPROTOZERO_INCLUDE_DIR=${GITHUB_WORKSPACE}/../protozero/include
        shell: bash

