layer:
  id: "wifidb"
  description: |
      The place layer consists of wifidb points from(https://wifidb.net/wifidb/),
  fields:
    ssid: The WifiDB [`ssid`] value of the POI.
    mac : The WifiDB [`mac`] value of the POI.
    sectype:
      description: |
          The **sectype** field marks the security level of the access point.
          1 is open, 2 is wep, 3 is secure
      values: [1, 2, 3]
    nt:
      description: |
          Network Type
    radio:
      description: |
          Radio Type
    chan:
      description: |
          Channel the access point is on
    auth:
      description: |
          Authentication Type
    encry:
      description: |
          Encryption Type
    btx:
      description: |
          Basic Connection Speeds
    otx:
      description: |
          Other Connection Speeds
    points:
      description: |
          Number of points in the wifidb
    fa:
      description: |
          First Active
    la:
      description: |
          Last Active
    lat:
      description: |
          Latitude
    lon:
      description: |
          Longitude
    alt:
      description: |
          Altitude
    manuf:
      description: |
          Manufacturer
  buffer_size: 256
  datasource:
    geometry_field: geometry
    key_field: osm_id
    key_field_as_attribute: no
    query: (SELECT osm_id, geometry, ssid, mac, sectype, nt, radio, chan, auth, encry, btx, otx, points, fa, la, lat, lon, alt, manuf FROM wdb_point(!bbox!, z(!scale_denominator!), !pixel_width!)) AS t
schema:

  - ./layer.sql
datasources:
  - type: imposm3
    mapping_file: ./mapping.yaml
