tables:
  lake_polygon:
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: validated_geometry
    - name: area
      type: area
    - name: name
      key: name
      type: string
    mapping:
      water:
      - lake
    type: polygon