name: Build

runs:
    using: composite

    steps:
      - name: Configure
        run: |
          mkdir build
          cd build
          BOOST_ROOT=$BOOST_ROOT_1_72_0 cmake -LA .. \
           -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake \
           -DBUILD_HEADERS=OFF \
           -BUILD_DATA_TESTS=OFF \
           -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
           -DPROTOZERO_INCLUDE_DIR=${GITHUB_WORKSPACE}/../protozero/include
        shell: bash

