tables:
  # etldoc: imposm3 -> osm_marine_point
  marine_point:
    type: point
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: geometry
    - name: name
      key: name
      type: string
    - name: name_en
      key: name:en
      type: string
    - name: name_de
      key: name:de
      type: string
    - name: tags
      type: hstore_tags
    - name: place
      key: place
      type: string
    - name: rank
      key: rank
      type: integer
    filters:
      require:
        name: ["__any__"]
    mapping:
      place:
      - ocean
      - sea
