layer:
  id: "landuse"
  description: |
      Landuse is used to describe use of land by humans. At lower zoom levels this is
      from Natural Earth data for residential (urban) areas and at higher zoom levels mostly OSM `landuse` tags.
  buffer_size: 4
  fields:
    class:
      description: |
          Use the **class** to assign special colors to areas.
          Original value of either the
          [`amenity`](http://wiki.openstreetmap.org/wiki/Key:amenity),
          [`tourism`](http://wiki.openstreetmap.org/wiki/Key:tourism),
          [`landuse`](http://wiki.openstreetmap.org/wiki/Key:landuse),
          or [`leisure`](http://wiki.openstreetmap.org/wiki/Key:leisure) tag.
      values:
      - school
      - university
      - kindergarten
      - college
      - library
      - hospital
      - railway
      - cemetery
      - military
      - residential
      - commercial
      - industrial
      - retail
      - stadium
      - pitch
      - playground
      - theme_park
      - bus_station
      - zoo
  datasource:
    geometry_field: geometry
    query: (SELECT geometry, class FROM layer_landuse(!bbox!, z(!scale_denominator!))) AS t
schema:
  - ./landuse.sql
datasources:
  - type: imposm3
    mapping_file: ./mapping.yaml
