generalized_tables:
  # etldoc: imposm3 -> osm_landuse_polygon_gen7
  landuse_polygon_gen7:
    source: landuse_polygon_gen6
    tolerance: ZRES7
  # etldoc: imposm3 -> osm_landuse_polygon_gen6
  landuse_polygon_gen6:
    source: landuse_polygon_gen5
    sql_filter: area>power(ZRES6,2) AND (landuse='residential' OR place='suburb' OR place='neighbourhood')
    tolerance: ZRES8
  # etldoc: imposm3 -> osm_landuse_polygon_gen5
  landuse_polygon_gen5:
    source: landuse_polygon_gen4
    sql_filter: area>power(ZRES7,2)
    tolerance: ZRES9
  # etldoc: imposm3 -> osm_landuse_polygon_gen4
  landuse_polygon_gen4:
    source: landuse_polygon_gen3
    sql_filter: area>power(ZRES8,2)
    tolerance: ZRES10
  # etldoc: imposm3 -> osm_landuse_polygon_gen3
  landuse_polygon_gen3:
    source: landuse_polygon_gen2
    sql_filter: area>power(ZRES9,2)
    tolerance: ZRES11
  # etldoc: imposm3 -> osm_landuse_polygon_gen2
  landuse_polygon_gen2:
    source: landuse_polygon_gen1
    sql_filter: area>power(ZRES10,2)
    tolerance: ZRES12
  # etldoc: imposm3 -> osm_landuse_polygon_gen1
  landuse_polygon_gen1:
    source: landuse_polygon
    sql_filter: area>power(ZRES11,2) AND ST_IsValid(geometry)
    tolerance: ZRES13

tables:
  # etldoc: imposm3 -> osm_landuse_polygon
  landuse_polygon:
    type: polygon
    columns:
    - name: osm_id
      type: id
    - name: geometry
      type: validated_geometry
    - name: landuse
      key: landuse
      type: string
    - name: amenity
      key: amenity
      type: string
    - name: leisure
      key: leisure
      type: string
    - name: tourism
      key: tourism
      type: string
    - name: place
      key: place
      type: string
    - name: waterway
      key: waterway
      type: string
    - name: area
      type: area
    mapping:
      landuse:
      - railway
      - cemetery
      - military
      # zoning
      - residential
      - commercial
      - industrial
      - garages
      - retail
      amenity:
      - bus_station
      - school
      - university
      - kindergarten
      - college
      - library
      - hospital
      leisure:
      - stadium
      - pitch
      - playground
      - track
      tourism:
      - theme_park
      - zoo
      place:
      - suburb
      - neighbourhood
      waterway:
      - dam
