dist: xenial
group: travis_latest
language: python
sudo: false
stages:
  - lint
  - test
  - name: deploy
    if: tag IS present
cache:
  directories:
    - $GDALINST
    - ~/.cache/pip
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
matrix:
  include:
    - python: 3.7
      stage: lint
      env: TOXENV=lint
      addons: skip
      before_install: skip
      after_success: skip
    - python: 3.7
      stage: lint
      env: TOXENV=docs
      addons: skip
      before_install: skip
      after_success: skip
    - python: 3.7
      stage: lint
      env: TOXENV=manifest
      addons: skip
      before_install: skip
      after_success: skip
    - python: 3.7
      stage: lint
      env: TOXENV=pypi-description
      addons: skip
      before_install: skip
      after_success: skip
    - python: 2.7
      stage: test
      env:
        - TOXENV=py27-gdal2.3.3
        - GDALVERSION=2.3.3
    - python: 3.6
      stage: test
      env:
        - TOXENV=py36-gdal2.3.3
        - GDALVERSION=2.3.3
    - python: 3.7
      stage: test
      env:
        - TOXENV=py37-gdal2.3.3
        - GDALVERSION=2.3.3
    - python: 3.8
      stage: test
      env:
        - TOXENV=py38-gdal2.3.3
        - GDALVERSION=2.3.3
    - python: 2.7
      stage: test
      env:
        - TOXENV=py27-gdal2.4.0
        - GDALVERSION=2.4.0
    - python: 3.6
      stage: test
      env:
        - TOXENV=py36-gdal2.4.0
        - GDALVERSION=2.4.0
    - python: 3.7
      stage: test
      env:
        - TOXENV=py37-gdal2.4.0
        - GDALVERSION=2.4.0
    - python: 3.8
      stage: test
      env:
        - TOXENV=py38-gdal2.4.0
        - GDALVERSION=2.4.0
    - python: 3.7
      stage: deploy
      env:
        - TOXENV=py37-gdal2.4.0
        - GDALVERSION=2.4.0
      deploy:
        provider: pypi
        user: fitodic
        password:
          secure: fRCyr8zsP/knk21KWzALM77oOvtUfN0y6cQVR9foUZkeGqg/s54u4twFJukWmqpFBaSICLNKJI/mkQqWh1WNAcBBmUIyzcAJDYf+EQBbFU5qyI7OY154mZgnYX/dCyEA+sDZq/77SU1n8C/idT8pEIaz8Mul1DPKOVyQIkHjgb1GOOc10SdeHruDZQ6/dyBPBOjIuUNYQHQ5qzE9NSZJruuLJB2W3K/cEp5Dm0R2I3czqBTgHOF8iWS36IDjyAJY5FKqcATvJp7NHI53laiHzlP7ilijUEQt0utXG3GUc9r8p+CIohWgdd2Fd5KAELeKBVT38aCY5XkmHAgxtlWdM7LykVYuLVUpuizZaIIgqYQmk8M1IECiOuEwLVQy9KQsa+t814b4+068TnwFsNVodGUonIzMV1ejoW11v0PNoWTLlOcNzb932RboaTl7fA6EfhPLzDDUSI/g8Yj1JgxPlopWE0W+o3EQDnSGnb4by3JY2yhiLK432TMoj6IVSYzHH7sk1fPkjKcL7qqczx+wnaw0pb7c4kFKKFAaT5H05ex66HkbG/BRK+AW6q6hURA4SFqersP33PwyFSUysYF6hvpCAs9tkwtKc0kQWs0Jil6/CEdmmpoc+ZttB1IC6xyLow0yqM76QiaSun5purJBI9GzdwQL+eKlUp7BbiricGA=
        skip_cleanup: true
        skip_existing: true
        distributions: "sdist bdist_wheel"
        on:
          tags: true
          branch: master

addons:
  apt:
    packages:
    - gdal-bin
    - libproj-dev
    - libhdf5-serial-dev
    - libpng12-dev
    - libgdal-dev
    - libatlas-dev
    - libatlas-base-dev
    - gfortran
before_install:
  - . ./.travis/install_gdal.sh
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
  - export GDAL_DATA=$GDALINST/gdal-$GDALVERSION/share/gdal
  - export PROJ_LIB=/usr/share/proj
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - gdal-config --version
  - "if [ $(gdal-config --version) == \"$GDALVERSION\" ]; then echo \"Using gdal $GDALVERSION\"; else echo \"NOT using gdal $GDALVERSION as expected; aborting\"; exit 1; fi"
install:
  - pip install -U pip tox coveralls
script:
  - tox
after_success:
  - coveralls
